# Generated by Django 4.1.7 on 2023-02-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sponge_flavour', models.CharField(choices=[('vanilla', 'Vanilla'), ('chocolate', 'Chocolate'), ('strawberry', 'Strawberry'), ('cherry', 'Cherry'), ('coffee', 'Coffee')], max_length=20)),
                ('frosting_flavour', models.CharField(choices=[('vanilla', 'Vanilla'), ('chocolate', 'Chocolate'), ('strawberry', 'Strawberry'), ('cherry', 'Cherry'), ('coffee', 'Coffee')], max_length=20)),
                ('frosting_type', models.CharField(choices=[('buttercream', 'Buttercream'), ('cream_cheese', 'Cream cheese'), ('fondant', 'Fondant')], max_length=20)),
            ],
        ),
    ]
